### ISSUE TITLE
EMN booster field error

### ISSUE THREAD

**Issue by Didero** [mtgjson/mtgjson#203]
The booster field for the Eldritch Moon (EMN) set has a nested list, which I don't think is correct.
I don't really feel knowledgeable enough about Magic to fix it and send a pull request though.

**Comment by Xeevee** [comment]
Have just come across the same issue, below is the example, as Rare's and Mythic Rare's are nested under "Common" I believe this must be a mistake?

```
booster: [
    [
        "rare",
        "mythic rare"
    ],
    "uncommon",
    "uncommon",
    "uncommon",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    [
        "common",
        [
            "double faced rare",
            "double faced mythic rare"
        ]
    ],
    [
        "double faced common",
        "double faced uncommon"
    ],
    "land",
    "marketing"
]
```

**Comment by tritoch** [comment]
This is correct.  In that common slot, you can have EITHER a common (non-dfc), or a dfc rare, or a dfc mythic.

**Comment by Xeevee** [comment]
Hi @tritoch,

Then surely the correct JSON format should be:

````
booster: [
    [
        "rare",
        "mythic rare"
    ],
    "uncommon",
    "uncommon",
    "uncommon",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    "common",
    [
        "common",
        "double faced rare",
        "double faced mythic rare"
    ],
    [
        "double faced common",
        "double faced uncommon"
    ],
    "land",
    "marketing"
]
````

**Comment by tritoch** [comment]
Also see #189 

As far as I know, EMN and SOI should have the same booster field.

**Comment by Didero** [comment]
From looking at the JSON set files, it seems SOI did get fixed, but the same mistake is still in EMN.json

**Comment by tritoch** [comment]
Fixed in codebase, but not in live json files.

**Comment by Didero** [comment]
But the error is also still in the zipfile you download from mtgjson.com's front page, which is where most people get their card data from, presumably.
When and how will that get this update?
(Sorry if that sounds grumpy. I'm curious, not stomping my feet)

**Comment by Didero** [comment]
The last few updates haven't solved this issue, so I thought I'd bring it up again (Sorry if that's not allowed).
I'm not entirely sure how MTGjson collects its data, but the accepted pull request changes a source file, and doesn't fix the actual EMN data file. My (closed) PR does fix the problem in the live file, so could you please accept that one? Or tell me what I need to change to get it accepted. I'd like to help solve this. Thanks.

**Comment by lsmoura** [comment]
Hello, @Didero 

Below is the information from http://mtgjson.com/json/EMN-x.json

`"booster":[["rare","mythic rare"],"uncommon","uncommon","uncommon","common","common","common","common","common","common","common","common",["common",["double faced rare","double faced mythic rare"]],["double faced common","double faced uncommon"],"land","marketing"]`

Is it wrong? Am I missing something?

Thanks for helping!

**Comment by Didero** [comment]
Thanks for the quick reply!

The problem is that there is a nested list in there.
From the end, before the marketing, land, and double-faced common/uncommon, there is:
`["common",["double faced rare","double faced mythic rare"]]`
while it should be
`"common",["double faced rare","double faced mythic rare"]`
The "common" shouldn't be in the list, and because the "common" got added somehow, it became a list  within a list.

I'm not sure if I'm phrasing myself clearly, I hope you can see what I mean :/

**Comment by lsmoura** [comment]
I see what you mean. But I think both you and mtgjson are wrong... Maybe the right value is:

`"booster":[["rare","mythic rare"],"uncommon","uncommon","uncommon","common","common","common","common","common","common","common","common",["common","double faced rare","double faced mythic rare"],["double faced common","double faced uncommon"],"land","marketing"]`? This way we have 15 cards + marketing.

If I change to the way you're saying, there will always be two double-faced cards on each booster and 16 cards + marketing.

**Comment by Didero** [comment]
It would make sense if it was the same for EMN as it is in SOI, yeah. So your suggestion is most likely correct.
Thanks for looking into it!
Do you want me to make the change and send a pull request, or is it easier for you to change it yourself?

**Comment by lsmoura** [comment]
@Didero I can't promise when I'll be able to do this myself, but to commit a PR and deploy it takes me just a few seconds.

If you can do it, please, do and tag this issue on your PR to make my life a little easier.

Thanks!

**Comment by Didero** [comment]
Thanks for the quick merge and fix!
